services:
  frontend:
    build: 
      target: dev-frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      target: dev-backend
    volumes:
      - ./backend:/app
    networks:
      - app
      - api
    ports:
      - "3001:3001"

networks:
  app:
  api: