services:
  frontend:
    build: 
      context: ./frontend
      target: dev-frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      target: dev-backend
    networks:
      - app
      - api
    ports:
      - "3001:3001"

networks:
  app:
  api: