services:
  frontend:
    build: 
      context: ./frontend
      target: client-build
    ports:
      - "3000:80"
    restart: always
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      target: prod-backend
    networks:
      - app
      - api
    ports:
      - "3001:3001"

networks:
  app:
  api: