services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: always
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      target: prod
    networks:
      - app
      - api
    ports:
      - "8000:8000"

networks:
  app:
  api: