services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: build
    image: stephglobals/deploy-frontend:1
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      target: prod
    image: stephglobals/deploy-backend:1
    networks:
      - app
      - api
    ports:
      - "8000:8000"

networks:
  app:
  api: