services:
  frontend:
    build: 
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
    networks:
      - app
      - api
    ports:
      - "8000:8000"

networks:
  app:
  api: